FROM openjdk:8-jdk-alpine
ADD build/libs/tw-citibike-apis-producer0.1.0.jar /app.jar
ENTRYPOINT java ${JAVA_OPTIONS} -jar /app.jar --spring.profiles.active=station-marseille --spring.profiles.active=docker
